### ISSUE TITLE
E: Unable to locate package bt-reload-headphones

### ISSUE THREAD

**Issue by gl517** [valderman/bt-reload-headphones#1]
Copied commands into Ubuntu terminal. On doing install, I got message:

N: Ignoring file 'ekblad-cc-disco' in directory '/etc/apt/sources.list.d/' as it has no filename extension

E: Unable to locate package bt-reload-headphones

**Comment by valderman** [comment]
Oops, I forgot that the `ekblad-cc-disco` file needs to be called `ekblad-cc-disco.list` instead. If you just rename it (`sudo mv /etc/apt/sources.list.d/ekblad-cc-disco /etc/apt/sources.list.d/ekblad-cc-disco.list`) and then run `sudo apt update && sudo apt install bt-reload-headphones` it should work.

**Comment by heyakyra** [comment]
Is there any upstream discussion on fixing profile switching in bluez?

Another workaround was posted here: https://gist.github.com/egelev/2e6b57d5a8ba62cf6df6fff2878c3fd4

But now the issue seems to have swapped
